name = "demofyit"
compatibility_date = "2023-12-01"
pages_build_output_dir = ".svelte-kit/output/client"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
# Environment variables will be set in Cloudflare Pages dashboard
# SENDGRID_API_KEY = "your_key_here"
# SENDGRID_FROM_EMAIL = "your_email_here" 
# SENDGRID_TO_EMAIL = "your_email_here"
